#################################################
# DO Community Playbooks: Initial Server Setup
#################################################
---
- hosts: localhost
  connection: local
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install Prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

# Sudo Group Setup
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Add 'hchauhan' to 'wheel' group
      user:
        name: hchauhan
        group: hchauhan
        groups: wheel
        append: yes

# Install Packages
    - name: Update apt
      apt: update_cache=yes

    - name: Installing packages
      apt: name={{ all_packages }} state=latest

    - name: Add 'hchauhan' to 'libvirt-qemu' and 'libvirt-dnsmasq' groups
      user:
        name: hchauhan
        groups: libvirt-qemu libvirt-dnsmasq
        append: yes

