---
sys_packages: [ 'curl', 'vim', 'git-all', 'ufw', 'emacs-nox', 'xcscope-el', 'build-essential', 'libmpc-dev', 'libgmp3-dev',
		'asciidoctor', 'ruby-asciidoctor-pdf', 'python3-pip', 'ninja-build', 'libglib2.0-dev', 'libpixman-1-dev',
                'duf', 'quilt', 'meson' ]
openwrt_packages: [ 'clang', 'flex', 'bison', 'g++', 'gawk', 'gcc-multilib', 'g++-multilib', 'gettext',
		 'git', 'libncurses5-dev', 'libssl-dev', 'python3-distutils', 'rsync', 'unzip', 'zlib1g-dev',
		 'file', 'wget' ]
