all_packages: [ 'curl', 'vim', 'git-all', 'ufw', 'emacs-nox', 'xcscope-el', 'build-essential', 'libmpc-dev', 'libgmp3-dev',
                'asciidoctor', 'ruby-asciidoctor-pdf', 'python3-pip', 'ninja-build', 'libglib2.0-dev', 'libpixman-1-dev',
                'duf', 'quilt', 'meson', 'htop', 'bashtop', 'cpufetch', 'neofetch', 'sl', 'python3-psutil', 'git-completion',
                'bash-completion', 'clang', 'flex', 'bison', 'g++', 'gawk', 'gettext', 'git', 'libncurses5-dev', 'libssl-dev',
                'python3-distutils-extra', 'rsync', 'unzip', 'zlib1g-dev', 'file', 'wget', 'fonts-fantasque-sans', 'virt-manager',
                'tigervnc-standalone-server', 'tigervnc-viewer', 'doas', 'nextcloud-desktop', 'mosh', 'sshfs', 'gparted', 'vlc',
		'tmux' ]
